INSERT INTO TBL_EMPLOYEES (first_name, last_name, main_skill, email, title, notes)
VALUES
('Rowena', 'Leeming', 'Java', 'rleeming0@bbc.co.uk', 'A', 'notes abc xy'),
('Alvinia', 'Delong', 'Java', 'adelong1@altervista.org', 'B', ''),
('Leodora', 'Burry', 'Java', 'lburry2@example.com', 'C', ''),
('Karen', 'Oaten', 'Java', 'koaten3@ihg.com', 'D', ''),
('Mariele', 'Huke', 'Java', 'mhuke4@washingtonpost.com', 'Research Assistant IV', ''),
('Grata', 'Widdowes', 'Angular', 'gwiddowes5@cargocollective.com', 'Actuary' ,''),
('Donna', 'Roadknight', 'Angular', 'droadknight6@apache.org', 'Mechanical Systems Engineer', ''),
('Tommi', 'Nowland', 'Angular', 'tnowland7@biblegateway.com', 'Senior Developer', ''),
('Tonya', 'Teresia', 'Angular', 'tteresia8@boston.com', 'Assistant Manager', ''),
('Steffen', 'Yon', 'Python', 'syon9@ocn.ne.jp', 'Senior Sales Associate', ''),
('Consalve', 'Willes', 'Python', 'cwillesa@linkedin.com', 'Programmer I', ''),
('Jeanelle', 'Lambertz', 'Python', 'jlambertzb@nymag.com', 'Operator', ''),
('Odelia', 'Loker', 'DevOps', 'olokerc@gov.uk', 'Developer I', ''),
('Briano', 'Shawell', 'DevOps', 'bshawelld@posterous.com', 'Research Assistant IV',''),
('Tarrance', 'Mainston', '.Net', 'tmainstone@cmu.edu', 'Research Nurse', ''),
('Torrence', 'Gehring', 'Go', 'tgehringf@a8.net', 'Geological Engineer', ''),
('Augie', 'Pionter', 'PHP', 'apionterg@ehow.com', 'Senior Financial Analyst', ''),
('Marillin', 'Aveson', '.Net', 'mavesonh@shop-pro.jp', 'Technical Writer', ''),
('Jacquelyn', 'Moreby', '.Net','jmorebyi@slashdot.org', 'Executive Secretary', ''),
('Glenn', 'Bangley', 'IOS','gbangleyj@prlog.org', 'Account Executive', ''),
('Isidoro', 'Glave', 'Android','iglavek@tamu.edu', 'Compensation Analyst', ''),
('Cchaddie', 'Spatarul', 'React','cspatarull@sun.com', 'Business Systems Development Analyst', '');