DROP TABLE IF EXISTS TBL_EMPLOYEES;

CREATE TABLE TBL_EMPLOYEES (
  id int AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  main_skill VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  notes VARCHAR(250) DEFAULT NULL
);